(()=>{
'use strict';
const $=s=>document.querySelector(s);
const LIVE='/ai/tag/data/live-quotes.json';
let marketMeta=null;
const parseFeedHealth=()=>{const text=$('#status')?.textContent||'';const m=text.match(/(\d+)\s*\/\s*(\d+)\s*feeds/i);return m?{ok:Number(m[1]),total:Number(m[2])}:{ok:0,total:0};};
function nyClock(){try{const parts=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date()).filter(p=>p.type!=='literal').map(p=>[p.type,p.value]));const weekday=parts.weekday;const mins=Number(parts.hour)*60+Number(parts.minute);const businessDay=!['Sat','Sun'].includes(weekday);return{businessDay,mins,regular:businessDay&&mins>=570&&mins<960,extended:businessDay&&mins>=240&&mins<=1200};}catch{return{businessDay:false,mins:null,regular:false,extended:false}}}
const ageMin=iso=>{if(!iso)return null;const t=new Date(iso).getTime();return Number.isFinite(t)?Math.max(0,(Date.now()-t)/60000):null};
async function loadMarketMeta(){try{const r=await fetch(`${LIVE}?truth=${Date.now()}`,{cache:'no-store'});if(!r.ok)return null;const p=await r.json();marketMeta={session:p.marketClockSession||p.session||'unknown',freshCount:Number(p.freshCount)||0,count:Number(p.count)||0,requested:Number(p.requested)||0,updatedAt:p.updatedAtET||p.updatedAtUTC||p.updatedAt||null,dataConfidence:p.dataConfidence||'UNKNOWN'};return marketMeta}catch{return null}}
function addPromotionGates(){document.querySelectorAll('.opp-card').forEach(card=>{card.querySelector('.promotion-gate')?.remove();const badges=[...card.querySelectorAll('.badges .badge')];const sharia=badges[1]?.textContent?.trim()||'';const dataLabel=badges.find(b=>['LOW','MEDIUM','HIGH','SESSION FINAL'].includes(b.textContent.trim()))?.textContent?.trim()||'';const reasons=[];if(dataLabel==='LOW')reasons.push('جودة بيانات السعر منخفضة');if(sharia==='UNVERIFIED')reasons.push('التصنيف الشرعي غير متحقق');if(sharia==='CONFLICT_REVIEW')reasons.push('التصنيف الشرعي يحتاج مراجعة');if(!reasons.length)return;const gate=document.createElement('div');gate.className='promotion-gate';gate.textContent=`غير جاهزة للترقية: ${reasons.join(' · ')}`;const why=card.querySelector('.why');(why||card).insertAdjacentElement(why?'afterend':'beforeend',gate);});}
function updateMarketTruth(){const notice=$('.notice');if(!notice)return;const title=notice.querySelector('b'),detail=notice.querySelector('div > span:last-child'),feeds=parseFeedHealth(),m=marketMeta,clock=nyClock();let quality='review',headline='جارٍ التحقق من حالة السوق الفعلية',copy='نجاح الاتصال بالمصادر لا يعني أن أسعار السوق طازجة.';if(feeds.total&&feeds.ok===0){quality='blocked';headline='تعذر الوصول إلى مصادر السوق';copy='لا تُعرض الحالات الحالية كفرص تنفيذية حتى عودة مصادر البيانات.';}else if(!m){quality='review';headline='المصادر متصلة — لم يكتمل التحقق من توقيت السوق';copy=`المصادر المتاحة ${feeds.ok}/${feeds.total||'—'}، لكن لم يتم التحقق بعد من freshness الفعلي للأسعار.`;}else{const age=ageMin(m.updatedAt),stale=age==null||age>15;if(clock.regular&&(m.session==='closed'||m.session==='pre-market'||stale||m.freshCount<=0)){quality='blocked';headline='نافذة التداول مفتوحة — لكن تغذية الأسعار الحية متأخرة أو غير متصلة';copy=`حالة المصدر=${m.session} · fresh=${m.freshCount} · عمر التغذية=${age==null?'غير معروف':Math.round(age)+' دقيقة'}. أوقفت TAGX أي ادعاء بوجود أسعار حية حتى وصول snapshot حديث.`;}else if(m.session==='closed'){quality='review';headline='السوق خارج الجلسة العادية — المعروض آخر بيانات موثقة + أحداث وأخبار لاحقة';copy=`آخر تغذية سوقية: ${m.count||m.requested||'—'} سهم، fresh اللحظي=${m.freshCount}. تستخدم TAGX آخر جلسة للتحليل التحضيري ولا تصفها بأنها بيانات حية.`;}else if(stale||m.freshCount<=0){quality='blocked';headline='بيانات السوق غير حديثة بما يكفي';copy=`حالة المصدر=${m.session} · التغطية=${m.count||m.requested||'—'} · fresh=${m.freshCount} · عمر التغذية=${age==null?'غير معروف':Math.round(age)+' دقيقة'}.`;}else{quality='live';headline=m.session==='regular'?'السوق مفتوح وتوجد أسعار حية موثقة':'توجد تغذية سوق حديثة موثقة';copy=`${m.freshCount} سعرًا حديثًا من ${m.count||m.requested||'—'} · عمر التغذية ${Math.round(age||0)} دقيقة · الحالة ${m.session}.`;}}notice.dataset.quality=quality;if(title)title.textContent=headline;if(detail)detail.textContent=copy;addPromotionGates();}
async function refreshTruth(){await loadMarketMeta();updateMarketTruth();}
function scheduleTruthChecks(){refreshTruth();[500,1500,3000].forEach(ms=>setTimeout(updateMarketTruth,ms));}
window.addEventListener('DOMContentLoaded',scheduleTruthChecks,{once:true});window.addEventListener('load',scheduleTruthChecks,{once:true});$('#refreshBtn')?.addEventListener('click',()=>setTimeout(refreshTruth,250));document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshTruth();});
})();